<a href="https://colab.research.google.com/github/mahfuz978/Kaggle-Challenge/blob/main/House_Price_Prediction_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# House Price Prediction Project

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import pandas as pd

In [3]:
# read the training data and testing data
train = pd.read_csv("/content/drive/MyDrive/Tech IS/Kaggle Challenge/train.csv")
test = pd.read_csv("/content/drive/MyDrive/Tech IS/Kaggle Challenge/test.csv")
train.head()

   Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0   1          60       RL  ...        WD         Normal    208500
1   2          20       RL  ...        WD         Normal    181500
2   3          60       RL  ...        WD         Normal    223500
3   4          70       RL  ...        WD        Abnorml    140000
4   5          60       RL  ...        WD         Normal    250000

[5 rows x 81 columns]

In [4]:
test.head()

     Id  MSSubClass MSZoning  ...  YrSold  SaleType SaleCondition
0  1461          20       RH  ...    2010        WD        Normal
1  1462          20       RL  ...    2010        WD        Normal
2  1463          60       RL  ...    2010        WD        Normal
3  1464          60       RL  ...    2010        WD        Normal
4  1465         120       RL  ...    2010        WD        Normal

[5 rows x 80 columns]

In [5]:
train.shape

(1460, 81)

In [6]:
test.shape

(1459, 80)

In [7]:
train = train.select_dtypes(include=["float64","int64"])

In [8]:
train.columns

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold', 'SalePrice'],
      dtype='object')

In [9]:
# These are the features that can affect the price
Features = ['MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond','YearBuilt', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal']
Target = "SalePrice"

In [10]:
# train = train[Features]
# test = test[Features]
print(train.head())
print(test.head())
print(train.shape)
print(test.shape)

   Id  MSSubClass  LotFrontage  LotArea  ...  MiscVal  MoSold  YrSold  SalePrice
0   1          60         65.0     8450  ...        0       2    2008     208500
1   2          20         80.0     9600  ...        0       5    2007     181500
2   3          60         68.0    11250  ...        0       9    2008     223500
3   4          70         60.0     9550  ...        0       2    2006     140000
4   5          60         84.0    14260  ...        0      12    2008     250000

[5 rows x 38 columns]
     Id  MSSubClass MSZoning  ...  YrSold  SaleType SaleCondition
0  1461          20       RH  ...    2010        WD        Normal
1  1462          20       RL  ...    2010        WD        Normal
2  1463          60       RL  ...    2010        WD        Normal
3  1464          60       RL  ...    2010        WD        Normal
4  1465         120       RL  ...    2010        WD        Normal

[5 rows x 80 columns]
(1460, 38)
(1459, 80)

In [11]:
train[Features].describe()

        MSSubClass  LotFrontage  ...     PoolArea       MiscVal
count  1460.000000  1201.000000  ...  1460.000000   1460.000000
mean     56.897260    70.049958  ...     2.758904     43.489041
std      42.300571    24.284752  ...    40.177307    496.123024
min      20.000000    21.000000  ...     0.000000      0.000000
25%      20.000000    59.000000  ...     0.000000      0.000000
50%      50.000000    69.000000  ...     0.000000      0.000000
75%      70.000000    80.000000  ...     0.000000      0.000000
max     190.000000   313.000000  ...   738.000000  15500.000000

[8 rows x 32 columns]

In [12]:
train[Features].dtypes

MSSubClass         int64
LotFrontage      float64
LotArea            int64
OverallQual        int64
OverallCond        int64
YearBuilt          int64
MasVnrArea       float64
BsmtFinSF1         int64
BsmtFinSF2         int64
BsmtUnfSF          int64
TotalBsmtSF        int64
1stFlrSF           int64
2ndFlrSF           int64
LowQualFinSF       int64
GrLivArea          int64
BsmtFullBath       int64
BsmtHalfBath       int64
FullBath           int64
HalfBath           int64
BedroomAbvGr       int64
KitchenAbvGr       int64
TotRmsAbvGrd       int64
Fireplaces         int64
GarageCars         int64
GarageArea         int64
WoodDeckSF         int64
OpenPorchSF        int64
EnclosedPorch      int64
3SsnPorch          int64
ScreenPorch        int64
PoolArea           int64
MiscVal            int64
dtype: object

In [13]:
train[Features].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 32 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   LotFrontage    1201 non-null   float64
 2   LotArea        1460 non-null   int64
 3   OverallQual    1460 non-null   int64
 4   OverallCond    1460 non-null   int64
 5   YearBuilt      1460 non-null   int64
 6   MasVnrArea     1452 non-null   float64
 7   BsmtFinSF1     1460 non-null   int64
 8   BsmtFinSF2     1460 non-null   int64
 9   BsmtUnfSF      1460 non-null   int64
 10  TotalBsmtSF    1460 non-null   int64
 11  1stFlrSF       1460 non-null   int64
 12  2ndFlrSF       1460 non-null   int64
 13  LowQualFinSF   1460 non-null   int64
 14  GrLivArea      1460 non-null   int64
 15  BsmtFullBath   1460 non-null   int64
 16  BsmtHalfBath   1460 non-null   int64
 17  FullBath       1460 non-null   int64
 18  HalfBath       1460 non-null   int64
 19  BedroomAbvGr   1460 non-null   int64
 20  KitchenAbvGr   1460 non-null   int64
 21  TotRmsAbvGrd   1460 non-null   int64
 22  Fireplaces     1460 non-null   int64
 23  GarageCars     1460 non-null   int64
 24  GarageArea     1460 non-null   int64
 25  WoodDeckSF     1460 non-null   int64
 26  OpenPorchSF    1460 non-null   int64
 27  EnclosedPorch  1460 non-null   int64
 28  3SsnPorch      1460 non-null   int64
 29  ScreenPorch    1460 non-null   int64
 30  PoolArea       1460 non-null   int64
 31  MiscVal        1460 non-null   int64
dtypes: float64(2), int64(30)
memory usage: 365.1 KB

In [14]:
null = train[Features].isnull().sum()
null[null>0].sort_values()

MasVnrArea       8
LotFrontage    259
dtype: int64

In [15]:
train[Features].head(2)

   MSSubClass  LotFrontage  LotArea  ...  ScreenPorch  PoolArea  MiscVal
0          60         65.0     8450  ...            0         0        0
1          20         80.0     9600  ...            0         0        0

[2 rows x 32 columns]

In [16]:
train[Target].head(2)

0    208500
1    181500
Name: SalePrice, dtype: int64

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(train[Features], train[Target], test_size=0.2, random_state=42)
print('The training and testing feature: ', X_train.shape, y_train.shape)
print('The training and testing target: ', X_val.shape, y_val.shape)

The training and testing feature:  (1168, 32) (1168,)
The training and testing target:  (292, 32) (292,)

In [18]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.pipeline import make_pipeline
scaler = StandardScaler()
model = LinearRegression()
imputer = SimpleImputer()
pipe = make_pipeline(imputer, scaler, model)
pipe.fit(X_train, y_train)
pipe.predict(X_val)
pipe.score(X_val, y_val)

0.823731721771003

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.pipeline import make_pipeline
scaler = StandardScaler()
model = LinearRegression()
imputer = IterativeImputer()
pipe = make_pipeline(imputer, scaler, model)
pipe.fit(X_train, y_train)
pipe.predict(X_val)
pipe.score(X_val, y_val)

0.8251989608529675

In [20]:
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.pipeline import make_pipeline
scaler = MinMaxScaler()
model = LinearRegression()
imputer = KNNImputer()
pipe = make_pipeline(imputer,scaler, model)
pipe.fit(X_train, y_train)
pipe.predict(X_val)
pipe.score(X_val, y_val)

0.8255549564249789

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.pipeline import make_pipeline
scaler = StandardScaler()
model = LinearRegression()
imputer = KNNImputer()
pipe = make_pipeline(imputer,scaler, model)
pipe.fit(X_train, y_train)
pipe.predict(X_val)
pipe.score(X_val, y_val)

0.8255632281210223

In [22]:
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.pipeline import make_pipeline
scaler = StandardScaler()
model = Ridge()
imputer = KNNImputer()
pipe = make_pipeline(imputer,scaler, model)
pipe.fit(X_train, y_train)
pipe.predict(X_val)
pipe.score(X_val, y_val)

0.8255681032530557

In [23]:
from sklearn.linear_model import Lasso
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.pipeline import make_pipeline
scaler = StandardScaler()
model = Lasso(max_iter=1000000000)
imputer = KNNImputer()
pipe = make_pipeline(imputer,scaler, model)
pipe.fit(X_train, y_train)
pipe.predict(X_val)
pipe.score(X_val, y_val)

0.8255580016886876

In [24]:
import xgboost
from xgboost import XGBRegressor
# from sklearn.ensemble import XGBRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.pipeline import make_pipeline
scaler = MinMaxScaler()
model = XGBRegressor(objective ='reg:squarederror',
                     n_estimators=1000, max_depth=7, eta=0.1, subsample=0.7, colsample_bytree=0.8, random_state = 42)
imputer = KNNImputer()
pipe = make_pipeline(imputer,scaler, model)
pipe.fit(X_train, y_train)
pipe.predict(X_val)
pipe.score(X_val, y_val)

0.8867309393485396

In [25]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.pipeline import make_pipeline
scaler = MinMaxScaler()
model = BaggingRegressor(n_estimators=2000, random_state=42)
imputer = KNNImputer()
pipe = make_pipeline(imputer,scaler, model)
pipe.fit(X_train, y_train)
pipe.predict(X_val)
pipe.score(X_val, y_val)

0.8908157933683467

In [26]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.pipeline import make_pipeline
scaler = MinMaxScaler()
model = BaggingRegressor(base_estimator=None, 
                         bootstrap=True, 
                         bootstrap_features=False,
                         max_features=1.0, 
                         max_samples=1.0, 
                         n_estimators=1500,
                         random_state=42)
imputer = KNNImputer()
pipe = make_pipeline(imputer,scaler, model)
pipe.fit(X_train, y_train)
pipe.predict(X_val)
pipe.score(X_val, y_val)

0.8909729916195575

In [27]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.pipeline import make_pipeline
scaler = MinMaxScaler()
model = RandomForestRegressor(random_state=42, n_estimators=1000)
imputer = KNNImputer()
pipe = make_pipeline(imputer,scaler, model)
pipe.fit(X_train, y_train)
pipe.predict(X_val)
pipe.score(X_val, y_val)

0.8911289381616763

### Now that I have a model in Mind We can submit

In [28]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer
from sklearn.pipeline import make_pipeline
scaler = MinMaxScaler()
model = RandomForestRegressor(random_state=42, n_estimators=1000)
imputer = KNNImputer()
pipe = make_pipeline(imputer,scaler, model)
# Here we are fitting the test 
pipe.fit(train[Features],train[Target])
predicted = pipe.predict(test[Features])

In [29]:
dd = pd.read_csv('/content/drive/MyDrive/Tech IS/Kaggle Challenge/sample_submission.csv')
print(dd.head())
dd.shape

     Id      SalePrice
0  1461  169277.052498
1  1462  187758.393989
2  1463  183583.683570
3  1464  179317.477511
4  1465  150730.079977

(1459, 2)

In [30]:
predicted_data = {"Id":test.Id,
                  "SalePrice":predicted}
submission_data = pd.DataFrame(predicted_data)
submission_data.shape

(1459, 2)

In [31]:
submission_data.head()

     Id   SalePrice
0  1461  129427.815
1  1462  157354.985
2  1463  179937.632
3  1464  181810.557
4  1465  198172.348

In [32]:
from google.colab import files
submission_data.to_csv("SalePrice_Prediction.csv", index=False)
files.download("SalePrice_Prediction.csv")